#### 1. Импортируйте пакет numpy под именем `np` (★☆☆)


In [ ]:
import numpy as np

#### 2. Создайте нулевой вектор размера 10 (★☆☆)


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Как узнать объем памяти любого массива (★☆☆)


In [ ]:
import sys

arr = np.arange(1,10)
#sys.getsizeof(arr)

print("Размер массива:",sys.getsizeof(arr))

Размер массива 184


#### 4. Создайте вектор со значениями от 10 до 49. (★☆☆)


In [ ]:
arr = np.arange(10, 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5. Создайте обратный вектор из вектора в задании 4 (первый элемент становится последним) (★☆☆)


In [ ]:
arr = np.arange(10, 50)

rev_vec1 = np.flip(arr)
print("Первый вариант",rev_vec1)

rev_vec2 = vec[::-1]
print("Второй вариант",rev_vec2)

Первый вариант [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
Второй вариант [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 6. Создайте матрицу 3x3 со значениями от 0 до 8. (★☆☆)


In [ ]:
matr1 = np.arange(9).reshape(3, 3)
print("Первый вариант:")
print(matr1)
#print("Тип данных:", matr2.dtype)

matr2 = np.zeros((3,3))
matr2 += np.arange(9).reshape(3,3)
print("Второй вариант")
print(matr2)
#print("Тип данных:", matr2.dtype)

Первый вариант:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Тип данных: float64
Второй вариант
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
Тип данных: float64


#### 7. Найти индексы ненулевых элементов из [1,2,0,0,4,0 (★☆☆)


In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
nonzero = np.nonzero(arr)

nonzero

Индексы ненулевых элементов: (array([0, 1, 4]),)


#### 8. Создайте массив 3x3x3 со случайными значениями (★☆☆)


In [ ]:
arr = np.random.rand(3, 3, 3)
arr

array([[[0.59685313, 0.40729512, 0.18171183],
        [0.98604764, 0.68128005, 0.86211374],
        [0.70052304, 0.11186871, 0.98547002]],

       [[0.02868028, 0.00589984, 0.06755788],
        [0.43471774, 0.46868849, 0.81885362],
        [0.69457159, 0.5744587 , 0.50558805]],

       [[0.92709912, 0.79970999, 0.53231004],
        [0.21315543, 0.87999467, 0.9585069 ],
        [0.06182656, 0.32887903, 0.29826541]]])

#### 9. Создайте массив 10x10 со случайными значениями и найдите минимальное и максимальное значения. (★☆☆)


In [ ]:
arr = np.random.rand(10,10)
#print("Массив", arr)

min = np.min(arr)
print("Минимум:", min)

max = np.max(arr)
print("Максимум:", max)

print(arr)

Минимум: 0.015697638801423608
Максимум: 0.9977974865380609
[[0.17686102 0.0737962  0.46689583 0.6329146  0.33741357 0.22819197
  0.68250662 0.91775194 0.44405271 0.74820721]
 [0.20133229 0.10345441 0.96124295 0.09504992 0.32216095 0.61858728
  0.78357813 0.74950523 0.96572353 0.33559598]
 [0.68501331 0.15769672 0.39020512 0.7429556  0.63547106 0.81512429
  0.87841262 0.33996451 0.83798722 0.86725963]
 [0.26244597 0.75436701 0.28039519 0.22038643 0.42674716 0.09784834
  0.42967669 0.78033692 0.31606077 0.54975651]
 [0.75890062 0.1515657  0.36120284 0.66890881 0.72401092 0.65236792
  0.66163822 0.21060012 0.34212443 0.57129843]
 [0.59042622 0.96985503 0.19301691 0.2386159  0.73925012 0.36227444
  0.49993357 0.3887088  0.78526855 0.8620317 ]
 [0.60833264 0.63337949 0.10149792 0.94051004 0.99779749 0.31741955
  0.26862461 0.27224367 0.93286237 0.303196  ]
 [0.98001256 0.78900929 0.85546719 0.90126827 0.53317311 0.79130594
  0.39859676 0.01569764 0.97345158 0.36785006]
 [0.60546921 0.449888

#### 10. Создайте случайный вектор размера 30 и найдите среднее значение(★☆☆)


In [ ]:
arr = np.random.randint(30)
#print(arr)
sr = np.mean(arr)
print ("Среднее значение:", sr)

Среднее значение: 21.0


#### 11. Создайте массив 2d 2x3 c 1 на границе и 0 внутри (★☆☆)


In [ ]:
arr = np.ones((2, 3))

arr[0, :] = 0
arr[-1, :] = 0
arr[:, 0] = 1
arr[:, -1] = 1

print(arr)

array([[1., 1., 1.],
       [1., 1., 1.]])

#### 12. Каков результат следующего выражения? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```


In [ ]:
np.nan # np.nan - не число
False # NaN не равен ни одному значению
False # любое стравнение с nun возвращает false
NaN # все арифметические операции с nan возвращают nan
True # nan пренадлежит множесву nan
False # оганичение в точности

nan

#### 13. Рассмотрим массив размера (6,7,8). Каков индекс (x,y,z) 100-го элемента? (★☆☆)


In [ ]:
arr = (6, 7, 8)

# Считаем с 0
index = 99

x = 99 % arr[0]
y = (99 // arr[0] // arr[1])
z = 99 // (arr[0]*arr[1])

print("Индексы (x, y, z) 100-го элемента:", (x, y, z))

Индексы (x, y, z) 100-го элемента: (3, 2, 2)


#### 14. Умножить матрицу 5x3 на матрицу 3x2(★☆☆)


In [ ]:
np.dot(np.random.random((5, 3)), np.random.random((3, 2)))

array([[1.31531319, 0.42214744],
       [1.33792645, 0.61240857],
       [1.66828697, 0.60546563],
       [1.52990473, 0.5841782 ],
       [2.06559829, 0.70713672]])

#### 15. Создайте одномерный массив со случайными значениями от 1 до 10, инвертируйте (поменяйте местами) все элементы, со значениями 3 и 8. (★☆☆)


In [ ]:
arr = np.random.randint(0, 11, size=10)
print("Массив до:   ", arr)

arr = np.where(arr == 3, 8, np.where(arr == 8, 3, arr))

print("Массив после:", arr)

Массив до:    [ 3  5  7  8  1  1  9  2  4 10]
Массив после: [ 8  5  7  3  1  1  9  2  4 10]


#### 16. Каков результат следующих выражений? (★☆☆)

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```


In [ ]:
np.array([np.nan]).astype(int).astype(float)

<ipython-input-36-ea171f4782f5>:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

In [ ]:
#nan # деление на 0 передает не опреденный результат
0 # целое от неопределенности 0
np.array([np.nan]).astype(int).astype(float)  #????????????????????????????????????


<ipython-input-43-b8092ad32736>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 17. Как найти общие значения между двумя массивами? (★☆☆)


In [ ]:
arr1 = np.random.randint(0,11, size = 5)
arr2 = np.random.randint(0,11, size = 5)

arr = np.intersect1d(arr1, arr2)

print(arr1)
print(arr2)
print("Общие значение между двумя массивами:", arr)

[0 3 8 4 7]
[9 7 6 6 5]
Общие значение между двумя массивами: [7]


#### 18. Как вычислить ((A+B)\*(-A/2)) с заменой массива А (без копирования)? (★★☆)


In [ ]:
A = np.random.randint(8, size=5)
B = np.random.randint(5, size=5)
A = (A+B)*(-A/2)
A

array([-21. ,  -1. , -24. ,   0. , -24.5])

#### 19. Создайте матрицу 5x5 со значениями строк от 0 до 4. (★★☆)


In [ ]:
arr = np.zeros((5, 5))

arr[:, 0] = 0
arr[:, 1] = 1
arr[:, 2] = 2
arr[:, 3] = 3
arr[:, 4] = 4

print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 20. Создайте вектор размера 10 со значениями в диапазоне от 0 до 1, исключая 1 и 0 (★★☆)


In [ ]:
arr = np.array(np.random.random(10))
arr

array([0.13565288, 0.34716358, 0.80302552, 0.44542385, 0.80549499,
       0.38059344, 0.82398851, 0.48848621, 0.65839844, 0.22154323])

#### 21. Создайте случайный вектор размера 10 и отсортируйте его (★★☆)


In [ ]:
arr1 = np.array(np.random.randint(0, 11, size = 10))
#arr1 = np.array(np.random.random(10))
print(arr1)

arr2 = np.sort(arr1)
print(arr2)

[10  1  3  5  8  4  4  0  6 10]
[ 0  1  3  4  4  5  6  8 10 10]


#### 22. Можно ли суммировать небольшой массив быстрее, чем np.sum? (★★☆)


In [ ]:
ar2 = np.random.randint(0, 11, size = 3)
%time print(sum(ar1)) # результат в ms

ar2 = np.random.randint(0, 11, size = 3)
%time print(np.sum(ar2)) #результат в µs

#нельзя

11
CPU times: user 1.12 ms, sys: 0 ns, total: 1.12 ms
Wall time: 2.23 ms
2
CPU times: user 0 ns, sys: 591 µs, total: 591 µs
Wall time: 590 µs


#### 23. Рассмотрим два случайных массива A и B, проверьте, равны ли они(★★☆)


In [ ]:
arr1 = np.random.randint(0, 11, size=(np.random.randint(1, 3, size = 2)))
arr2= np.random.randint(0, 11, size=(np.random.randint(1, 3, size = 2)))

are_equal = np.array_equal(arr1, arr2)

print("Массив arr1:")
print(arr1)
print("Массив arr2:")
print(arr2)
print("Массивы arr1 и arr2 равны:", are_equal)

Массив arr1:
[[5]]
Массив arr2:
[[0 8]
 [8 4]]
Массивы arr1 и arr2 равны: False


#### 24. Создайте случайный вектор размера 10 и замените максимальное значение на 0 (★★☆)


In [ ]:
arr1 = np.random.randint(100, size = 10)
print ("Массив до:   ", arr1)
arr2 = np.where(arr1 == np.max(arr1), 0, arr1)
print ("Массив после:", arr2)

Массив до:    [67  1 80 86 43 28 98 15 62 25]
Массив после: [67  1 80 86 43 28  0 15 62 25]


#### 25. Распечатайте минимальное и максимальное представимое значение для каждого скалярного типа numpy (★★☆)


In [ ]:
print("Минимальное и максимальное значения для целочисленных типов данных:")
print("int8:", np.iinfo(np.int8).min, np.iinfo(np.int8).max)
print("int16:", np.iinfo(np.int16).min, np.iinfo(np.int16).max)
print("int32:", np.iinfo(np.int32).min, np.iinfo(np.int32).max)
print("int64:", np.iinfo(np.int64).min, np.iinfo(np.int64).max)
print("uint8:", np.iinfo(np.uint8).min, np.iinfo(np.uint8).max)
print("uint16:", np.iinfo(np.uint16).min, np.iinfo(np.uint16).max)
print("uint32:", np.iinfo(np.uint32).min, np.iinfo(np.uint32).max)
print("uint64:", np.iinfo(np.uint64).min, np.iinfo(np.uint64).max)

print("\nМинимальное и максимальное значения для вещественных типов данных:")
print("float16:", np.finfo(np.float16).min, np.finfo(np.float16).max)
print("float32:", np.finfo(np.float32).min, np.finfo(np.float32).max)
print("float64:", np.finfo(np.float64).min, np.finfo(np.float64).max)

#### 26. Как вывести все значения большого массива? (★★☆)


In [ ]:
np.set_printoptions(threshold=1001)
print(np.arange(1001))

#### 27. Рассмотрим случайный вектор формы (100,2), представляющий координаты, найдите расстояния между точками. (★★☆)


In [ ]:
arr1 = np.random.rand(100, 2)
x,y = np.atleast_2d(arr1[:,0], arr1[:,1])
arr2 =  np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(arr2)

[[0.         0.53569449 0.52194214 ... 1.02079534 0.49343646 0.64637015]
 [0.53569449 0.         0.91531629 ... 1.02589355 0.94240565 0.74808143]
 [0.52194214 0.91531629 0.         ... 0.74463751 0.11596879 0.43411243]
 ...
 [1.02079534 1.02589355 0.74463751 ... 0.         0.86030607 0.37616403]
 [0.49343646 0.94240565 0.11596879 ... 0.86030607 0.         0.54077217]
 [0.64637015 0.74808143 0.43411243 ... 0.37616403 0.54077217 0.        ]]


#### 28. Как преобразовать массив с плавающей запятой (32 бита) в целое число (32 бита) с заменой?


In [ ]:
arr1 = np.array(np.random.rand(10)*10, dtype=np.float32)
print("Массив до округления:")
print(arr1)

arr2 = arr1.astype(np.int32)
print("Массив после округления:")
print(arr2)

Массив до округления:
[0.3381394 2.4962966 9.615875  3.8587346 4.6231465 6.440818  7.487768
 1.7264519 6.3248296 2.3629975]
Массив после округления:
[0 2 9 3 4 6 7 1 6 2]


#### 29. Создайте массив из следующего файла: (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```


In [ ]:
from io import StringIO
arr = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")

np.genfromtxt(arr, delimiter=",")

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

#### 30. Вычтите среднее значение каждой строки случайной матрицы. (★★☆)


In [ ]:
arr = np.random.rand(np.random.randint(1, 7, size = 1)[0],np.random.randint(1, 6, size = 1)[0])
print("Матрица до вычитания среднего:")
print(arr)

for mas in arr:
  print("Среднее каждой строки - ", mas.mean())
  mas -= mas.mean()

print("Матрица после вычитания среднего:")
print(arr)

Матрица до вычитания среднего:
[[0.74866423 0.09997086 0.53170091 0.84047426]
 [0.80023535 0.13810802 0.81712856 0.10994624]
 [0.58724301 0.92182799 0.48103861 0.2882049 ]
 [0.56258915 0.22101316 0.05550101 0.04233921]
 [0.27753046 0.11624513 0.82578137 0.96269711]]
Среднее каждой строки -  0.5552025668707457
Среднее каждой строки -  0.4663545425862919
Среднее каждой строки -  0.5695786271672713
Среднее каждой строки -  0.22036063150871066
Среднее каждой строки -  0.5455635155922218
Матрица до вычитания среднего:
[[ 0.19346166 -0.45523171 -0.02350165  0.2852717 ]
 [ 0.33388081 -0.32824653  0.35077402 -0.3564083 ]
 [ 0.01766439  0.35224936 -0.08854001 -0.28137373]
 [ 0.34222852  0.00065253 -0.16485963 -0.17802142]
 [-0.26803306 -0.42931838  0.28021785  0.41713359]]


#### 31. Рассмотрим случайный вектор, как добавить 1 к каждому элементу, индексированному вторым вектором (будьте осторожны с повторяющимися индексами)? (★★★)


In [ ]:
arr1 = np.random.randint(0, 10, size = 10)
arr2 = np.random.randint(0, 10, size = 5)
print("Массив до:   " ,arr1)
#print(arr2)

arr2 = np.unique(np.sort(arr2))
#print(arr2)

i = 0
while (i < len(arr2)):
  if (arr2[i] <= 9):
    arr1[arr2[i]] = arr1[arr2[i]] + 1
  i = i + 1
print("Массив после:", arr1)

Массив до:    [8 8 6 3 2 8 3 1 5 3]
Массив после: [9 8 6 3 3 9 3 2 5 3]


In [ ]:
arr1 = np.random.randint(0, 10, size = 10)
arr2 = np.random.randint(0, 10, size = 5)
print("Массив до:   " ,arr1)
#print(arr2)

arr2 = np.unique(np.sort(arr2))
#print(arr2)

j = 0
while (j < len(arr2)):
  for i in range(len(arr1)):
    if (arr2[j] == i):
      arr1[i] = arr1[i] + 1
  j = j + 1
print("Массив после:", arr1)

Массив до:    [5 3 4 0 7 4 2 9 6 6]
Массив после: [ 5  4  5  0  7  4  2 10  6  7]


#### 32. Как перенести элементы вектора (X) в массив (F) на основе списка индексов (I)? (★★★)


In [ ]:
x = np.random.randint(0, 10, size = 10)
f = np.zeros((5,5), dtype=np.int32)
print(f)
print(x)
l = np.random.randint(0,4, size = (10, 2))
print(l)

for i in range (9):
  f[l[i][0]][l[i][1]]  = x[i]

print(f)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[6 1 0 1 4 2 7 2 8 4]
[[3 0]
 [2 2]
 [2 1]
 [1 0]
 [2 0]
 [2 2]
 [0 3]
 [1 3]
 [1 2]
 [3 1]]
[[0 0 0 7 0]
 [1 0 8 2 0]
 [4 0 2 0 0]
 [6 0 0 0 0]
 [0 0 0 0 0]]


#### 33. Рассматривая четырехмерный массив, как получить сумму сразу (в одну операцию) по двум последним осям? (★★★)


In [ ]:
arr1 = np.random.randint(0, 10, size=(2, 3, 4, 5))

arrsum = np.sum(arr1, axis=(-2, -1))

print("Сумма по двум последним осям:")
print(arrsum)

Сумма по двум последним осям:
[[83 88 95]
 [60 84 67]]


#### 34. Рассмотрим вектор [1, 2, 3, 4, 5], как построить новый вектор с 3 последовательными нулями, чередующимися между каждым значением? (★★★)


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])

arr2 = np.insert(arr1,np.repeat(np.arange(1, len(arr1)), 3), 0)

print(arr2)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.zeros(len(f) + (len(arr1)-1)*(3))
arr2[::4] = arr1

print(arr2)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 35. Рассмотрим массив размерности (5,5,3), как его умножить на массив размерностью (5,5)? (★★★)


In [ ]:
arr1 = np.random.random((5,5,3))
arr2 = np.random.random((5,5))
arr2 = arr2[:, :, np.newaxis] # дублирование на новую ось
print("Результат перемножения: ", np.multiply(arr1, arr2))

Результат перемножения:  [[[0.37833117 0.72058048 0.5058954 ]
  [0.94520992 0.29055934 0.39083212]
  [0.4054008  0.04015807 0.35657019]
  [0.09811    0.01716224 0.03254031]
  [0.32621511 0.10373271 0.2865374 ]]

 [[0.32819376 0.40637671 0.37232904]
  [0.15323207 0.13500912 0.2283486 ]
  [0.34860155 0.02258587 0.42922414]
  [0.33854787 0.30565145 0.45644935]
  [0.05659627 0.21516476 0.03007972]]

 [[0.45950246 0.5055568  0.03258154]
  [0.47545683 0.55622322 0.54613785]
  [0.59123548 0.05715278 0.69942475]
  [0.44491284 0.30342924 0.03374274]
  [0.54798368 0.39785027 0.31379278]]

 [[0.12096019 0.30436996 0.559957  ]
  [0.4277668  0.05839659 0.23806316]
  [0.27194436 0.14928508 0.22297854]
  [0.03767295 0.02805207 0.04354471]
  [0.23279604 0.17350459 0.12357368]]

 [[0.01830377 0.1372769  0.02531709]
  [0.30712958 0.07758505 0.29998101]
  [0.16233117 0.08029239 0.07781932]
  [0.37039156 0.26623329 0.35105568]
  [0.26802623 0.14586127 0.09368324]]]


#### 36. Как вычислить средние значения, используя скользящее окно по массиву? (★★★)


In [ ]:
def average(arr, winsize):
    #print(winsize)
    win = arr.shape[0] - winsize + 1
    avg_arr = np.zeros(win)

    for i in range(win):
        window = arr[i:i+winsize]
        avg_arr[i] = np.mean(window)

    return avg_arr

arr = np.arange(20)
print(average(arr, np.random.randint(1,10, size = 1)[0]))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]


#### 37. Рассмотрим одномерный массив Z, постройте из него двумерный массив, первая строка которого (Z[0],Z[1],Z[2]), а каждая последующая строка сдвинута на 1 (последняя строка должна быть (Z[ -3],Z[-2],Z[-1]) (★★★)


In [ ]:
def shift_array(Z):
    n = Z.shape[0] - 2
    arr = np.empty((n, 3), dtype=arr.dtype)
    for i in range(n):
        arr[i] = Z[i:i+3]
    return arr

Z = np.arange(1, 10)
print(shift_array(arr))

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 38. Рассмотрим 2 набора точек P0,P1, описывающих линии (2d), и набор точек P. Как вычислить расстояние от каждой точки j (P[j]) до каждой линии i (P0[i],P1[i])?(★★★)


In [ ]:
P0 = np.random.randint(0, 10, (5,2))
P1 = np.random.randint(0,10,(5,2))
P = np.random.randint(0, 10, (5,2))

diff_P0_P = P0 - P[:, np.newaxis, :]
diff_P1_P = P1 - P[:, np.newaxis, :]


len = np.linalg.norm(diff_P1_P - diff_P0_P, axis=2)

area = np.cross(diff_P0_P, diff_P1_P, axis=2)
dist = np.abs(area) / len

print(dist)

[[3.79473319 2.97683363 4.25817748 4.11096096 2.23606798]
 [0.9486833  1.48841682 3.4340141  1.26491106 0.4472136 ]
 [2.84604989 3.72104204 2.33512959 3.16227766 2.23606798]
 [5.37587202 4.83735465 5.76914369 5.69209979 3.57770876]
 [1.8973666  4.21718098 2.60985072 2.21359436 1.34164079]]


#### 39. Рассмотрим массив Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], как сгенерировать массив R = [[1,2,3, 4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)


In [ ]:
Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
np.reshape([Z[i:i+4] for i in range(11)], (11, 4))

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 40. Найдите ранг случайной матрицы (★★★)


In [ ]:
arr = np.random.randint(0, 10, size=(np.random.randint(4,10, size = 2)))
print(arr)
print("Ранг этой матрицы:", np.linalg.matrix_rank(arr))

[[0 8 6 6 7 0 3 0]
 [9 6 3 5 0 1 7 9]
 [4 4 1 6 7 8 4 7]
 [3 8 5 7 7 4 9 1]
 [4 8 0 9 9 3 8 3]
 [7 7 7 2 1 5 9 8]
 [7 5 6 6 4 8 0 0]]
Ранг этой матрицы: 7


#### 41. Как найти наиболее часто встречающееся значение в массиве?


In [ ]:
arr = np.random.randint(0,10,size = 20)
print("Сгенерированный массив:", arr)

unique, counts = np.unique(arr, return_counts=True)
k_v = dict(zip(unique, counts))

print("Пары значение: количесво:", k_v )
max_count = counts.max()

print("Наиболее часто встречающиеся элементы:")
for k, v in k_v.items():
    if v == max_count:
        print(k)

Сгенерированный массив: [4 7 8 4 6 6 4 1 4 4 1 2 1 0 2 4 1 7 1 7]
Пары значение: количесво: {0: 1, 1: 5, 2: 2, 4: 6, 6: 2, 7: 3, 8: 1}
Наиболее часто встречающиеся элементы:
4


#### 42. Рассмотрим два массива A и B формы (8,3) и (2,2). Как найти строки A, содержащие элементы каждой строки B, независимо от порядка элементов в B? (★★★)


In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
print("Массив A:")
print(A)
print("Массив B:\n")
print(B)

c = []

for row_b in B:
    for row_a in A:
        if np.all(np.isin(row_b, row_a)) and not any(np.array_equal(row_a, row) for row in c):
            c.append(row_a)

c = np.array(c)

print("\nМассив c:")
print(c)

In [ ]:
A = np.random.randint(0,5,(8,3))
B= np.random.randint(0,5,(2,2))
print("Массив A:")
print(A)
print("\nМассив B:")
print(B)

c = []
unique_rows = set()

for row_b in B:
    for row_a in A:
        if np.all(np.isin(row_b, row_a)) and tuple(row_a) not in unique_rows:
            c.append(row_a)
            unique_rows.add(tuple(row_a))

c = np.array(c)

print("\nМассив c:")
print(c)

#### 43. Как извлечь уникальные значения из 2-х двумерных массивов?(★★★)


In [ ]:
arr1 = np.random.randint(0,10,(3,3))
#print(arr1)
arr2 = np.random.randint(0,10,(3,3))
#print(arr2)

arr = np.concatenate((arr1, arr2))
print(arr)

unique, counts = np.unique(arr, return_counts=True)
k_v = dict(zip(unique, counts))

print("Пары значение: количесво:", k_v )
print("Уникальные значения:")
for k, v in k_v.items():
    if v == 1:
        print(k)

[[9 3 3]
 [6 0 1]
 [3 7 4]
 [3 2 9]
 [5 5 9]
 [7 3 6]]
Пары значение: количесво: {0: 1, 1: 1, 2: 1, 3: 5, 4: 1, 5: 2, 6: 2, 7: 2, 9: 3}
Уникальные значения:
0
1
2
4
